############################
# HYPRIDLE
# CachyOS + Hyprland
############################

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Bloquear tela após 5 minutos de inatividade
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Desligar tela 2 minutos após bloquear (7min total)
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
