############################
# HYPRLOCK
# CachyOS + Hyprland
############################

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

# Fundo com blur do wallpaper
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.7
    contrast = 0.9
    vibrancy = 0.2
}

# Relógio - hora
label {
    monitor =
    text = $TIME
    color = rgba(c9cdc7ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# Relógio - data
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d de %B"
    color = rgba(c9cdc7aa)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# Campo de senha
input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgba(D78F7788)
    inner_color = rgba(0f0f0fcc)
    font_color = rgba(c9cdc7ff)
    fade_on_empty = true
    placeholder_text = <i>senha...</i>
    hide_input = false
    check_color = rgba(76A299ff)
    fail_color = rgba(9B4C40ff)
    fail_text = <i>incorreta</i>
    capslock_color = rgba(908B76ff)
    position = 0, -120
    halign = center
    valign = center
}
